server:
  port: 8160

spring:
  application:
    name: service-user
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost/yygh_user?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: su360595304
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 192.168.227.134
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
mybatis-plus:
  mapper-locations: classpath:com/gu/yygh/user/mapper/xml/*.xml

wx:
  open:
    app_id: wxed9954c01bb89b47
    app_secret: a7482517235173ddb4083788de60b90e
    redirect_url: http://localhost:8160/api/ucenter/wx/callback
yygh:
  baseUrl: http://localhost:3000