server:
  port: 8206

spring:
  application:
    name: service-order

  # 环境
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yygh_order?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: su360595304

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      uri: mongodb://192.168.227.134/yygh_hosp
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  rabbitmq:
    port: 5627
    username: admin
    password: 123456
    addresses: 192.168.227.134

  redis:
    host: 192.168.227.134

alipay:
  appId: 2021000119629314
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCQjNw01beV6dgXrt6n83mPR8biRhFWPDgHdzWrHWKIoKFpAP7WFTJrhyo1g7JDzvNlJnXBLKKBFIkWQsk0W201VGca0sKpd77ySZX4l67MLTlXSq+GZjR85RnwgFLeSWkc/RXjXOVzuZt6lOlPQEKPeurhxWajp55K/Uc5Q10Sg9CbD0BDTP+n9uEzz/KUGnA6ppbim4loauzfNAjmPIh82Jd1+DuDATRDhVFjhfqhyz1D1ajcV1y0/Lt6MhgJLEKpmdYQ2AVnHxJt/wsaxI2W4s9m3cSRZVDW7zf8nO4GsNTpxA2Imx1izQgelyR3hKB37u5IlWxY4iFpjaVA9/r9AgMBAAECggEAMz270f7w1XPP5pVW2LK2pNQM7Klp++fc9MiNfdss0sIeddqke7+H4BZKIC5PQzpZjcHUfGYWNSvSbNHAAY9nZ0BETH3qA6kvRzROtZEPpdFiQk93aW1RrfSI/Xh/58yeNmiBGdgUfrGNLCcdjbp53eL04JPZjqocsviWBvaaR7Vo2zmkCx9evCVGci3JTy/U7TfpwkG01ySKBKWBmTbCBUAu96GDsW//Mb043lEtV4TzMQxFvDKQzRMZi+fiwgczkxI8PWwMRuiqmzIRz6eX0RWrs2uM7wadZ4c/lZxhLY9+YWsc9hVG7IbD1t3AHY7D/HpLsDldkRzsk7TfNhd4AQKBgQDcOad58zv4BEmd3im6Xh0YlWxDyiwmGl1nz/R6Aj22vFJPdCYs6junDkxY0nZfNvfolb+gWX8onmGdvOiAcLBnwpExQKP4yXvvAwdrAu8o9ZAeGpSvZGZ97jcb3uNAV4S9qOV98nUKE+3/Foz8Zk7SNDuPA69rvbE01Jz6TepsSQKBgQCoCCptZpitxXveOkZbgYZ3D5Oi2eVClx4UeTcGy2V7wekk1eoWJT+5+JylC6k4PG5dQMfak9rhlHJ+A8uL2Zu0h8NctPXhvX6gM6Sd9VmKyyLFpkya4J1dVOvdvMzSPzV625BMOTWfoTuX3g+LjpPv/ebDpipCE9jLmusriKpRFQKBgAJ5/4EmlBkQ60cENZHr9wXMwF/uyRpQl5ZQR16L4efJLF/KXZeJtswFJCSnkT823gjWjkYeW4i4Zz6f3jl7ivBPxtQ39uAYW/VvIkk4yjm6sTk1cVCbn29xG1uL4SBbG5oKaTJGZLyNRtLkjQdVmzNP9Q+BqhpbEsAWWAGUmLtJAoGBAJFhL0QkJikC2h71kHYPZMWSRov5ti+dC7tu/Lr2M8GVjh/+rF+orrA6d10c77XmIx6vs7pbfl75zu1UX0GKbvsNE2wcbTh4eRwmUmEQK/63rkgPj+vYNo7PsJrShOvLIHxBh2FLhiesmiDVUeHO5BQaOxQ/qgQto77VNG8f+SvZAoGBANAC0Xk1YHQued3rbBlUbvHU38iHA0qiDawtNcyQCEpIOtp6LZ+O2o0ajatYAAw185UbISYciD1JEywF05azgyZyxuZlIDzxyvU70dRyhIQu1Yb6o5VYQKAbR3tpchoGkXQ2nyMkSvkixV1RMR4DtIli6VMcWKLiF0i8XVDpXUvu
  format: json
  charset: utf-8
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjmbo5SWgYBGTh0GFk/4NsmbbO9QKTvYUD8dPXCPTyKb/9qe3Mag69hY2lpWgozX2JrAppS2QiodjsmbQW6TQh2noL/yKBJGMf0JMmIghNHSLpuHirTfoFHPlhMbwjLSJo9SAclsVbsfAK8z8JTuWfvFky3VzHttJvHg/HKuuz8q8w7MJa716fDiW00hqu8jlp58INrtnP47kkQlKtu8BP1f1xA6JUP1toPMPJ7PMLRtd0cIDD/8X6yeqdxHQz7sPhenMA3E6PaMRgkb10j3Jr3efmMNDLNIRgxDNRKM7HOa5cYZfK/Gg52EgcucWxe2JB/LZBLa2w3OFgXuiWaYRKQIDAQAB
  signType: RSA2