server:
  port: 8205
spring:
  application:
    name: service-oss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  redis:
#    host: 192.168.227.134
#    port: 6379
#    database: 0
#    timeout: 1800000
#    lettuce:
#      pool:
#        max-active: 20
#        max-wait: -1
#        max-idle: 5
#        min-idle: 0
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    bucket: xxxxxxxxxxxxxxxxxx
    accessKeyId: xxxxxxxxxxxxxxxxxx
    secret: xxxxxxxxxxxxxxx
